version: "3"
services:
  app:
    container_name: "customer_info_app"
    build: .
    ports:
      - "3020:3000"
    volumes:
      - .:/usr/src/app

  customer_dbpostgres:
    container_name: "customer_info_postgres"
    image: postgres:9.6
    ports:
      - "5441:5432" 
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_info
      
      
